@baseUrl = http://localhost:8000

### Ping
GET {{baseUrl}}/v1/auth/__ping

### Login (dùng username)
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456789"
}
