@baseUrl = http://localhost:8000

### Ping
GET {{baseUrl}}/v1/auth/__ping

### Register
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456789",
  "email": "testuser@gmail.com"
}

### REGISTER
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
  "username": "myadmin",
  "password": "123456789",
  "email": "admin@gmail.com"
}

### Ping user
GET {{baseUrl}}/v1/user/__ping

### Get users
GET {{baseUrl}}/v1/user/

### DELETE USER
DELETE {{baseUrl}}/v1/user/68a813e6fb9b42ccae18faa0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTgzODU4ZmU4ZGM5OTFkZjE4NGY4NiIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTc1NTg1NDk1MywiZXhwIjoxNzU2NDU5NzUzfQ.s2sXqBJhNzq4Uu7PVoyCaVA5tVUwz6P8lH_bsW-nn3w

### Login
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456789"
}

### Get user with role Admin
GET {{baseUrl}}/v1/user/68a83858fe8dc991df184f86
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTgzODU4ZmU4ZGM5OTFkZjE4NGY4NiIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTc1NTg1NTI2MCwiZXhwIjoxNzU2NDYwMDYwfQ.AapIbMT-WItL6hMZy0NtvO-TQ247048wBJi9jDEHYA4

### Refresh token
POST {{baseUrl}}/v1/auth/refresh
Cookie: refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTgzODU4ZmU4ZGM5OTFkZjE4NGY4NiIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTc1NjExNDYxMiwiZXhwIjoxNzg3NjUwNjEyfQ.RwWEqtRMqFOU_Wnzfl3n-TBnPD2D-48aQfz4i6SlroE

### Logout
POST {{baseUrl}}/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTgzODU4ZmU4ZGM5OTFkZjE4NGY4NiIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTc1NjExNTYzMywiZXhwIjoxNzU2MTE1NjYzfQ.z2VkvC62-btaNJ-sr2u6KKX0QaSGmOQKaf-llqW2VaE
