@baseUrl = http://localhost:8000

### Ping
GET {{baseUrl}}/v1/auth/__ping

### Register
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456789",
  "email": "testuser@gmail.com"
}

### REGISTER
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
  "username": "testuser2",
  "password": "123456789",
  "email": "testuser2@gmail.com"
}

## Ping user
GET {{baseUrl}}/v1/user/__ping

### Get users
GET {{baseUrl}}/v1/user/

### DELETE USER
DELETE {{baseUrl}}/v1/user/68a81392fb9b42ccae18fa9a

### Login
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456789"
}

### Get user with Token
GET {{baseUrl}}/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTgxMzdmZmI5YjQyY2NhZTE4ZmE5OCIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3NTU4NTEyMzcsImV4cCI6MTc1NTg1NDgzN30.bRAIlAYHSKRIOlR85Rsiek78wxXI9zT7msLYHMvIcT4

